spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/loooSwc/SpringcloudConfig/
          search-paths: workhelper
          default-label: master
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://47.104.111.123:8000/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
